name: Azure CI/CD

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    env:
      REGISTRY_SERVER: hvalfangstcontainerregistry.azurecr.io # See 'terraform.tf' for ACR name
      IMAGE_NAME: hvalfangstcontainerregistry.azurecr.io/hvalfangst-rust-crud-with-axum:latest
      RESOURCE_GROUP: hvalfangstresourcegroup
      DNS_NAME_LABEL: hvalfangst-rust-crud-with-axum
      CONTAINER_NAME: hvalfangst-rust-crud-with-axum
      LOCATION: West Europe

    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Azure Login with OpenID Connect
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}

      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          dns-name-label: ${{ env.DNS_NAME_LABEL }}
          name: ${{ env.CONTAINER_NAME }}
          image: ${{ env.IMAGE_NAME }}
          location: ${{ env.LOCATION }}
          registry-login-server: ${{ env.REGISTRY_SERVER }}
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}